const arr = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5];
const arrSet = new Set(arr);
const uniqueValue = [...new Set(arr)];
console.log("uniqueValue:", uniqueValue);
// arrSet.add(1);
// arrSet.add(2);
// arrSet.add(3);
// arrSet.add(4);
// arrSet.add(5);
// arrSet.add(5);
// arrSet.add(5);
console.log(arrSet);
// console.log(arrSet.size);
// console.log(arrSet.size);
// console.log(arrSet.has(4));
// console.log(arrSet.delete(3));
// console.log(arrSet.size);
// console.log(arrSet.clear());
// console.log(arrSet.size);
